export const COMPANIES = [
  {
    description: `Meta Platforms, Inc., doing business as Meta and formerly named Facebook, Inc., and TheFacebook, Inc., is an American multinational technology conglomerate based in Menlo Park, California. The company owns Facebook, Instagram, and WhatsApp, among other products and services.`,
    logoUrl: 'https://logo.clearbit.com/meta.com',
    name: 'Meta',
    slug: 'meta',
  },
  {
    description: `Google LLC is an American multinational technology company that focuses on search engine technology, online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial intelligence, and consumer electronics.`,
    logoUrl: 'https://logo.clearbit.com/google.com',
    name: 'Google',
    slug: 'google',
  },
  {
    description: `Apple Inc. is an American multinational technology company that specializes in consumer electronics, software and online services headquartered in Cupertino, California, United States.`,
    logoUrl: 'https://logo.clearbit.com/apple.com',
    name: 'Apple',
    slug: 'apple',
  },
  {
    description: `Amazon.com, Inc. is an American multinational technology company that focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence.`,
    logoUrl: 'https://logo.clearbit.com/amazon.com',
    name: 'Amazon',
    slug: 'amazon',
  },
  {
    description: `Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services headquartered at the Microsoft Redmond campus located in Redmond, Washington, United States.`,
    logoUrl: 'https://logo.clearbit.com/microsoft.com',
    name: 'Microsoft',
    slug: 'microsoft',
  },
  {
    description: `AlphaLab Capital Group is a technology-driven trading group that transacts over $2B daily in cryptoassets on 40+ exchanges, both centralized and decentralized.`,
    logoUrl: 'https://logo.clearbit.com/alphalab.capital',
    name: 'AlphaLab Capital',
    slug: 'alphalab',
  },
  {
    description: `Autodesk, Inc. is an American multinational software corporation that makes software products and services for the architecture, engineering, construction, manufacturing, media, education, and entertainment industries.`,
    logoUrl: 'https://logo.clearbit.com/autodesk.com',
    name: 'Autodesk',
    slug: 'autodesk',
  },
  {
    description: `The Bank of America Corporation (often abbreviated BofA or BoA) is an American multinational investment bank and financial services holding company headquartered at the Bank of America Corporate Center in Charlotte, North Carolina.`,
    logoUrl: 'https://logo.clearbit.com/bank-locations.com',
    name: 'Bank of America',
    slug: 'bankofamerica',
  },
  {
    description: `ByteDance Ltd. is a Chinese internet technology company headquartered in Beijing and incorporated in the Cayman Islands.`,
    logoUrl: 'https://logo.clearbit.com/bytedance.com',
    name: 'ByteDance',
    slug: 'bytedance',
  },
  {
    description: `Citibank, N.A. (N.A. stands for "National Association") is the primary U.S. banking subsidiary of financial services multinational Citigroup.`,
    logoUrl: 'https://logo.clearbit.com/citibank.com',
    name: 'CitiBank',
    slug: 'citibank',
  },
  {
    description: `Cloudflare, Inc. is an American content delivery network and DDoS mitigation company, founded in 2010.`,
    logoUrl: 'https://logo.clearbit.com/cloudflare.com',
    name: 'Cloudflare',
    slug: 'cloudflare',
  },
  {
    description: `ComfortDelGro Corporation is a multi-national land transport company listed on the Singapore Exchange, operating about 35,000 vehicles in seven countries.`,
    logoUrl: 'https://logo.clearbit.com/comfortdelgro.com',
    name: 'ComfortDelGro',
    slug: 'comfortdelgro',
  },
  {
    description: `Creative Technology Ltd. is a Singaporean multinational technology company headquartered in Jurong East, Singapore, with overseas offices in Shanghai, Tokyo, Dublin, and Silicon Valley (where in the US it is known as Creative Labs)`,
    logoUrl: 'https://logo.clearbit.com/creative.com',
    name: 'Creative',
    slug: 'creative',
  },
  {
    description: `Garena is a Singaporean game developer and publisher of free online games. It is the digital entertainment arm of parent company Sea Ltd, which was formerly named Garena.`,
    logoUrl: 'https://logo.clearbit.com/garena.ru',
    name: 'Garena',
    slug: 'garena',
  },
  {
    description: `GIC Private Limited is a sovereign wealth fund to manage Singapore's foreign reserves.`,
    logoUrl: 'https://logo.clearbit.com/gic.com.sg',
    name: 'GIC',
    slug: 'gic',
  },
  {
    description: `Goldman Sachs is an American multinational investment bank and financial services company.`,
    logoUrl: 'https://logo.clearbit.com/goldmansachs.com',
    name: 'Goldman Sachs',
    slug: 'goldmansachs',
  },
  {
    description: `The Government Technology Agency (GovTech) is a statutory board of the Government of Singapore, under the Prime Minister's Office.`,
    logoUrl: 'https://logo.clearbit.com/tech.gov.sg/',
    name: 'GovTech',
    slug: 'govtech',
  },
  {
    description: `Grasshopper is a leading Singaporean proprietary trading firm providing liquidity in global markets.`,
    logoUrl: 'https://logo.clearbit.com/grasshopperasia.com/',
    name: 'Grasshopper Asia',
    slug: 'grasshopperasia',
  },
  {
    description: `International Business Machines Corporation (IBM) is an American multinational technology corporation headquartered in Armonk, New York, with operations in over 171 countries.`,
    logoUrl: 'https://logo.clearbit.com/ibm.com',
    name: 'IBM',
    slug: 'ibm',
  },
  {
    description: `JPMorgan Chase & Co. is an American multinational investment bank and financial services holding company headquartered in New York City and incorporated in Delaware.`,
    logoUrl: 'https://logo.clearbit.com/jpmorgan.com',
    name: 'JPMorgan',
    slug: 'jpmorgan',
  },
  {
    description: `Jump Trading LLC is a proprietary trading firm with a focus on algorithmic and high-frequency trading strategies.`,
    logoUrl: 'https://logo.clearbit.com/jumptrading.com',
    name: 'Jump Trading',
    slug: 'jumptrading',
  },
  {
    description: `KPMG International Limited (or simply KPMG) is a multinational professional services network, and one of the Big Four accounting organizations.`,
    logoUrl: 'https://logo.clearbit.com/kpmg.com',
    name: 'KPMG',
    slug: 'kpmg',
  },
  {
    description: `NCS Group (also known as NCS Pte Ltd or "NCS", previously known as National Computer Systems) is a multinational information technology company headquartered in Singapore.`,
    logoUrl: 'https://logo.clearbit.com/ncs.com.sg',
    name: 'NCS',
    slug: 'ncs',
  },
  {
    description: `Ninja Van is a Singaporean logistics company. Founded in 2014, the company engages in last mile logistics and package delivery.`,
    logoUrl: 'https://logo.clearbit.com/ninjavan.co',
    name: 'Ninja Van',
    slug: 'ninjavan',
  },
  {
    description: `Open Government Products work on meaningful projects from healthcare to anti-scam technology. Use your skills to fix actual problems in the community and build a better Singapore.`,
    logoUrl: 'https://logo.clearbit.com/open.gov.sg',
    name: 'Open Government Products',
    slug: 'ogp',
  },
  {
    description: `Razer Inc. is an American-Singaporean multinational technology company that designs, develops, and sells consumer electronics, financial services, and gaming hardware.`,
    logoUrl: 'https://logo.clearbit.com/razer.com',
    name: 'Razer',
    slug: 'razer',
  },
  {
    description: `ShopBack is a cashback reward program available across the Asia-Pacific (APAC).`,
    logoUrl: 'https://logo.clearbit.com/shopback.com',
    name: 'ShopBack',
    slug: 'shopback',
  },
  {
    description: `Shopee Pte. Ltd. (Shopee) is a Singaporean multinational technology company that specialises in e-commerce.`,
    logoUrl: 'https://logo.clearbit.com/shopee.sg',
    name: 'Shopee',
    slug: 'shopee',
  },
  {
    description: `Stripe, Inc. is an Irish-American financial services and software as a service (SaaS) company dual-headquartered in South San Francisco, California, United States and Dublin, Ireland.`,
    logoUrl: 'https://logo.clearbit.com/stripe.com',
    name: 'Stripe',
    slug: 'stripe',
  },
  {
    description: `Thales Group is a French multinational company that designs, develops and manufactures electrical systems as well as devices and equipment for the aerospace, defence, transportation and security sectors.`,
    logoUrl: 'https://logo.clearbit.com/thalesgroup.com',
    name: 'Thales Group',
    slug: 'thalesgroup',
  },
  {
    description: `TikTok, known in China as Douyin, is a short-form video hosting service owned by Chinese company ByteDance.`,
    logoUrl: 'https://logo.clearbit.com/tiktok.com',
    name: 'Tiktok',
    slug: 'tiktok',
  },
  {
    description: `Visa Inc. is an American multinational financial services corporation headquartered in San Francisco, California.`,
    logoUrl: 'https://logo.clearbit.com/visa.com',
    name: 'Visa',
    slug: 'visa',
  },
  {
    description: `Zendesk is an American company headquartered in San Francisco, California. It provides software-as-a-service products related to customer support, sales, and other customer communications.`,
    logoUrl: 'https://logo.clearbit.com/zendesk.com',
    name: 'Zendesk',
    slug: 'zendesk',
  },
  {
    description: `99.co is Singapore's fastest growing property portal. With us, you'll feel right at home when searching for houses, condominiums, apartments and HDBs for sales & rent in Singapore.`,
    logoUrl: 'https://logo.clearbit.com/99.co',
    name: '99.co',
    slug: '99co',
  },
];
