export const JobTitleLabels = {
  'ai-engineer': 'Artificial Intelligence (AI) Engineer',
  'algorithms-engineer': 'Algorithms Engineer',
  'android-engineer': 'Android Software Engineer',
  'applications-engineer': 'Applications Engineer',
  'back-end-engineer': 'Back End Engineer',
  'business-analyst': 'Business Analyst',
  'business-engineer': 'Business Engineer',
  'capacity-engineer': 'Capacity Engineer',
  'customer-engineer': 'Customer Engineer',
  'data-analyst': 'Data Analyst',
  'data-engineer': 'Data Engineer',
  'data-scientist': 'Data Scientist',
  'devops-engineer': 'DevOps Engineer',
  'engineering-director': 'Engineering Director',
  'engineering-manager': 'Engineering Manager',
  'enterprise-engineer': 'Enterprise Engineer',
  'forward-deployed-engineer': 'Forward Deployed Engineer',
  'front-end-engineer': 'Front End Engineer',
  'full-stack-engineer': 'Full Stack Engineer',
  'gameplay-engineer': 'Gameplay Engineer',
  'hardware-engineer': 'Hardware Engineer',
  'infrastructure-engineer': 'Infrastructure Engineer',
  'ios-engineer': 'iOS Software Engineer',
  'machine-learning-engineer': 'Machine Learning (ML) Engineer',
  'machine-learning-researcher': 'Machine Learning (ML) Researcher',
  'mobile-engineer': 'Mobile Software Engineer (iOS + Android)',
  'networks-engineer': 'Networks Engineer',
  'partner-engineer': 'Partner Engineer',
  'product-engineer': 'Product Engineer',
  'product-manager': 'Product Manager',
  'production-engineer': 'Production Engineer',
  'project-manager': 'Project Manager',
  'release-engineer': 'Release Engineer',
  'research-engineer': 'Research Engineer',
  'research-scientist': 'Research Scientist',
  'rotational-engineer': 'Rotational Engineer',
  'sales-engineer': 'Sales Engineer',
  'security-engineer': 'Security Engineer',
  'site-reliability-engineer': 'Site Reliability Engineer (SRE)',
  'software-engineer': 'Software Engineer',
  'solutions-architect': 'Solutions Architect',
  'solutions-engineer': 'Solutions Engineer',
  'systems-analyst': 'Systems Analyst',
  'systems-engineer': 'Systems Engineer',
  'tech-ops-engineer': 'Tech Ops Engineer',
  'technical-program-manager': 'Technical Program Manager',
  'test-engineer': 'QA/Test Engineer (SDET)',
  'ux-engineer': 'User Experience (UX) Engineer',
};

export type JobTitleType = keyof typeof JobTitleLabels;

export function getLabelForJobTitleType(jobTitle: JobTitleType): string {
  return JobTitleLabels[jobTitle];
}
